{"uuid": "4c0a6f83-12b5-49c1-a195-e9dd4f3e1935", "children": ["d8a1defd-f9b8-4075-946a-ef0c7343fd5d", "1619d745-613f-43fb-b8ba-fb7c64f11134", "d37bb221-aa99-4ea6-9020-37294b293fd1", "2ddc88f9-2a23-4a70-b768-f95a953b85a7", "3b768cda-0dc5-4e94-8850-1ae120d9f911", "cb228059-224f-4e0b-8aa0-924f797b3a7a"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "NameError: Invalid response code.\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 77, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 543, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_ref[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 563, in push_config\n    self.sdk_client.check_response(\"POST\", resp, self.sdk_client.make_headers(), basic_cfg_str, uri)\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 153, in check_response\n    raise NameError(\"Invalid response code.\")\n"}, "attachments": [{"name": "ucentral_config: ", "source": "3e736bcb-cabb-4a1a-804e-6fe6a6c179f3-attachment.json", "type": "application/json"}, {"name": "/configure response: 400", "source": "9202f535-d7fa-4c5f-b916-6c15e673d99e-attachment.json", "type": "application/json"}], "start": 1637853180355, "stop": 1637853185341}], "start": 1637853180355, "stop": 1637853187454}