{"uuid": "730f76ae-ea0b-4ea9-8c90-dc695fa2f6e6", "children": ["3dd1ef4f-793e-4103-aa05-4145f88dfd4c", "92c4346c-dabb-4d63-8fc7-928cae33ea93", "695edf42-45af-4c3c-8362-5224a037a6a6", "69248c25-3df5-4f76-bc46-a6744f75c9aa", "9e363744-686e-4880-bf92-04b882cb8bf0", "1da2b2ef-e0c9-4ca2-a078-20a623d59fa0"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "NameError: Invalid response code.\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 77, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 543, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_ref[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 563, in push_config\n    self.sdk_client.check_response(\"POST\", resp, self.sdk_client.make_headers(), basic_cfg_str, uri)\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 153, in check_response\n    raise NameError(\"Invalid response code.\")\n"}, "attachments": [{"name": "ucentral_config: ", "source": "f4780413-0cd0-4ffb-a8c9-6a8034f47775-attachment.json", "type": "application/json"}, {"name": "/configure response: 400", "source": "49094eab-4689-425c-908b-40ee3d8e9282-attachment.json", "type": "application/json"}], "start": 1636671678355, "stop": 1636671683730}], "start": 1636671678355, "stop": 1636671685951}