{"uuid": "a2b10a50-fd8d-44af-9522-6a093d9290ae", "children": ["192097a5-2962-4d76-b706-23fe8e925446", "31a73829-8ed9-423b-871d-4c94dfacfa01", "d79f08b1-4f58-48bf-b750-8169541d693d", "1634a319-3160-4e1a-bbb9-01b7f016986a", "27453fc6-1c35-4489-8ca8-a5a4a8477b46", "7ec21451-e016-4c9b-b1f5-0e40c8ff4c3a"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "NameError: Invalid response code.\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 77, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 543, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_ref[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 563, in push_config\n    self.sdk_client.check_response(\"POST\", resp, self.sdk_client.make_headers(), basic_cfg_str, uri)\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 153, in check_response\n    raise NameError(\"Invalid response code.\")\n"}, "attachments": [{"name": "ucentral_config: ", "source": "e7fe1819-d4a7-4f35-9bf4-db859e80e3f2-attachment.json", "type": "application/json"}, {"name": "/configure response: 400", "source": "8c6bf9c6-1b2f-48da-b17a-5d5a1b71ab72-attachment.json", "type": "application/json"}], "start": 1637269766550, "stop": 1637269771958}], "start": 1637269766550, "stop": 1637269774157}