{"uuid": "a1c436b0-5ff7-49d8-aee7-e5c4eb7d8e82", "children": ["131a4424-ed54-4e0a-b9d2-28d42f22b870", "bd677ead-fc47-4ca9-8c1a-0ca8863118e9", "481b3e30-05d5-43ed-ba4f-489587a92ad1", "c507cde0-7483-4ce6-86d3-9b6c9e989660", "f948d932-57fe-4dbf-bf96-a67eb26e3d86", "007fc988-163e-4d67-9c2f-9822262d9bbe"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "NameError: Invalid response code.\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 77, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 543, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_ref[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 563, in push_config\n    self.sdk_client.check_response(\"POST\", resp, self.sdk_client.make_headers(), basic_cfg_str, uri)\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 153, in check_response\n    raise NameError(\"Invalid response code.\")\n"}, "attachments": [{"name": "ucentral_config: ", "source": "aca85552-4455-4b5f-8247-7674c63ea4ba-attachment.json", "type": "application/json"}, {"name": "/configure response: 400", "source": "b1b49dc4-5e8d-4188-a583-aa9ef00ec816-attachment.json", "type": "application/json"}], "start": 1637356957834, "stop": 1637356963471}], "start": 1637356957834, "stop": 1637356965411}