{"uuid": "5e14c25e-627b-4bfa-bc26-f36ee243891f", "children": ["ad82ad53-d57d-47ce-92f2-00e3bfe761bc", "d8c12848-ed73-465f-8df8-dfdf5aa5248a", "2ea97355-7864-4749-a0e6-2b866fdefac1", "cd897f0e-2c91-4f9b-9c34-63e682846bee", "4c0645f6-e3ef-469c-91c3-a5950518bb22", "30dee40c-9e51-4467-9e76-a959bfb25838"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "NameError: Invalid response code.\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 77, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 543, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_ref[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 563, in push_config\n    self.sdk_client.check_response(\"POST\", resp, self.sdk_client.make_headers(), basic_cfg_str, uri)\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 153, in check_response\n    raise NameError(\"Invalid response code.\")\n"}, "attachments": [{"name": "ucentral_config: ", "source": "2846df19-0aed-49fd-ba1f-51d4a5a203e4-attachment.json", "type": "application/json"}, {"name": "/configure response: 400", "source": "81558da3-75a1-4649-9b3e-f93eed7aecfb-attachment.json", "type": "application/json"}], "start": 1637356376312, "stop": 1637356381759}], "start": 1637356376311, "stop": 1637356383714}