{"uuid": "0ff3c415-8d41-4889-ba47-31fbaf949ad7", "children": ["0b262012-f9c2-4984-994d-7c67c5f593bb", "090fa51a-ec6c-4ede-9fc8-6159f905f268", "dc9b87de-381c-4824-97f9-64502c4eb3b7", "945d5cfc-4ad7-415a-a27e-c4113f2f303d", "3dfb25b6-7878-47dd-8b2c-71cdd52f81c8", "6ff98157-16f8-41ac-921e-1785226b2104"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "NameError: Invalid response code.\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 77, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 543, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_ref[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 563, in push_config\n    self.sdk_client.check_response(\"POST\", resp, self.sdk_client.make_headers(), basic_cfg_str, uri)\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 153, in check_response\n    raise NameError(\"Invalid response code.\")\n"}, "attachments": [{"name": "ucentral_config: ", "source": "02fe534e-2a68-4195-ade5-84f784b0f874-attachment.json", "type": "application/json"}, {"name": "/configure response: 400", "source": "81efd4b4-f406-4e8d-b407-59d5bb8982e2-attachment.json", "type": "application/json"}], "start": 1637701505268, "stop": 1637701512281}], "start": 1637701505268, "stop": 1637701514472}