{"uuid": "4fc5e939-8aa4-4a74-ac56-644daceedea6", "children": ["540ee289-50b9-4ee4-bdeb-14925c13c127", "2c2fcdeb-b7c7-4e28-9438-87f335273b01", "95d17e67-6241-437a-bbdf-b7d4bf27940e", "5409b84b-2c05-47d2-b1d5-7efdf6981107", "94c004c0-b1d2-435b-82f7-61d51a5fb6e0", "7b6ae0d5-bf49-443d-8e32-2912a31b5b73"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "NameError: Invalid response code.\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 77, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 543, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_ref[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 563, in push_config\n    self.sdk_client.check_response(\"POST\", resp, self.sdk_client.make_headers(), basic_cfg_str, uri)\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 153, in check_response\n    raise NameError(\"Invalid response code.\")\n"}, "attachments": [{"name": "ucentral_config: ", "source": "3fc21cb5-ae15-4d1c-9582-a43911193a73-attachment.json", "type": "application/json"}, {"name": "/configure response: 404", "source": "31f550dd-704d-4c46-a9b6-6120b93dcc7c-attachment.json", "type": "application/json"}], "start": 1638247880249, "stop": 1638247885057}], "start": 1638247880249, "stop": 1638247886966}