{"uuid": "36b5a440-0fbf-4b1b-ae58-9b65a511977b", "children": ["aa6ba829-f4d4-42ab-b61a-759aac3a0b98", "7cd441b3-abb9-4fb4-a69b-efdcf9fe8a30", "ba5c84a4-d927-4205-ae94-12956df4bca6", "7dc68801-ef8f-4d7f-af88-71f6be10109e", "e25778fd-783b-47e8-959d-d52fc8a992b2", "3de48111-3875-44be-9f94-239a7c911522"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "NameError: Invalid response code.\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 77, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 543, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_ref[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 563, in push_config\n    self.sdk_client.check_response(\"POST\", resp, self.sdk_client.make_headers(), basic_cfg_str, uri)\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 153, in check_response\n    raise NameError(\"Invalid response code.\")\n"}, "attachments": [{"name": "ucentral_config: ", "source": "7cb30d5f-697c-4401-8a3f-3ba2934dd409-attachment.json", "type": "application/json"}, {"name": "/configure response: 400", "source": "74ae3516-e4f3-40bd-bc1c-75dac8f8a5a5-attachment.json", "type": "application/json"}], "start": 1637701469653, "stop": 1637701477216}], "start": 1637701469653, "stop": 1637701479361}