{"uuid": "92a1c74a-d479-4df5-ad6f-ef7a633bb915", "children": ["64938d60-1807-41bd-9dec-2b7de13ad7ba", "b0463dd4-4401-4b03-8813-8205f1d3bec9", "7065643d-9cfb-459a-be86-e971ea736438", "92652def-be7b-41a0-95ef-dcd124c14f68", "8ed85975-d194-47e8-9763-1d5e8c051c9b", "ed96d0c7-afd0-4a16-9c6c-7c402e765172"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "NameError: Invalid response code.\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 77, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 543, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_ref[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 563, in push_config\n    self.sdk_client.check_response(\"POST\", resp, self.sdk_client.make_headers(), basic_cfg_str, uri)\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 153, in check_response\n    raise NameError(\"Invalid response code.\")\n"}, "attachments": [{"name": "ucentral_config: ", "source": "eea66c84-8dde-4830-affb-f5d17daae6b8-attachment.json", "type": "application/json"}, {"name": "/configure response: 400", "source": "7b776849-8fe5-4f85-bb37-7e3b5115b413-attachment.json", "type": "application/json"}], "start": 1637701461345, "stop": 1637701467536}], "start": 1637701461345, "stop": 1637701469647}