{"uuid": "57aefaba-b8c9-465a-a1a7-c53edcd8afe8", "children": ["caf700ca-5c3b-4326-b8e3-d41f0c378d06", "695ae72a-163b-46f7-a666-4e60c105b068", "47638545-8af5-4fa0-8f10-8be15b190ef7", "f3575960-420f-4735-9589-42865820b4f0", "7682df55-4087-4d82-84c9-ce63b4757578", "56c76ae5-f246-4343-bf5b-e7f9e8b5be06"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "NameError: Invalid response code.\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 77, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 543, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_ref[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 563, in push_config\n    self.sdk_client.check_response(\"POST\", resp, self.sdk_client.make_headers(), basic_cfg_str, uri)\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 153, in check_response\n    raise NameError(\"Invalid response code.\")\n"}, "attachments": [{"name": "ucentral_config: ", "source": "21c95c84-ceab-4d1d-bde5-1d5d06974812-attachment.json", "type": "application/json"}, {"name": "/configure response: 400", "source": "b389e6fe-2f72-4a7a-937c-04886bedc961-attachment.json", "type": "application/json"}], "start": 1637442337447, "stop": 1637442342398}], "start": 1637442337447, "stop": 1637442345342}